### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This library will improve performance and greatly reduce memory allocations through object pooling of SemaphoreSlim objects.

@JacobAtchley

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
Fixed tests @JacobAtchley

**Review by JacobAtchley — APPROVED** [review]

**Comment by MarkCiliaVincenti** [comment]
Cheers @JacobAtchley :) Hope to see a new NuGet package version released soon :)

**Comment by JacobAtchley** [comment]
@MarkCiliaVincenti Sorry for the late response. I got both your PRs merged and version bumped Jobba. 
We don't update this project as frequently as we do some others so we haven't set up versionize yet to do auto version bumps. Thanks for your contributions!

**Comment by MarkCiliaVincenti** [comment]
Cheers!

**Pull request merged**
